
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const ERROR_CLEAR = "ERROR_CLEAR";
export const ERROR_VALIDATION = "ERROR_VALIDATION";


export const ALUMNI_DATA_LIST = "ALUMNI_DATA_LIST";
export const ALUMNI_DATA_ADD = "ALUMNI_DATA_ADD";
export const ALUMNI_DATA_VIEW = "ALUMNI_DATA_VIEW";
export const ALUMNI_DATA_EDIT = "ALUMNI_DATA_EDIT";
export const ALUMNI_DATA_UPDATE = "ALUMNI_DATA_UPDATE";
export const ALUMNI_DATA_DELETE = "ALUMNI_DATA_DELETE";
export const ALUMNI_DATA_SEARCH = "ALUMNI_DATA_SEARCH";
export const ALUMNI_DATA_EDIT_CANCEL = "ALUMNI_DATA_EDIT_CANCEL";


export const NEW_ALUMNI_LIST = "NEW_ALUMNI_LIST";
export const NEW_ALUMNI_VIEW = "NEW_ALUMNI_VIEW";
export const NEW_ALUMNI_SEARCH = "NEW_ALUMNI_SEARCH";
export const NEW_ALUMNI_VERIFIED = "NEW_ALUMNI_VERIFIED";


export const ROLE_LOADING = "ROLE_LOADING";
export const ROLE_LIST = "ROLE_LIST";
export const ROLE_EDIT = "ROLE_EDIT";
export const ROLE_UPDATE = "ROLE_UPDATE";
export const ROLE_LIST_ADD = "ROLE_LIST_ADD";
export const PERMISSION_LIST = "PERMISSION_LIST";