export const LOGIN = "LOGIN";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_REQUIRED = "LOGIN_REQUIRED";
export const AUTH_USER_DETAIL = "AUTH_USER_DETAIL";

export const ERROR_CLEAR = "ERROR_CLEAR";
export const ERROR_VALIDATION = "ERROR_VALIDATION";


export const ALUMNI_DATA_LIST = "ALUMNI_DATA_LIST";
export const ALUMNI_DATA_ADD = "ALUMNI_DATA_ADD";
export const ALUMNI_DATA_VIEW = "ALUMNI_DATA_VIEW";
export const ALUMNI_DATA_EDIT = "ALUMNI_DATA_EDIT";
export const ALUMNI_DATA_UPDATE = "ALUMNI_DATA_UPDATE";
export const ALUMNI_DATA_DELETE = "ALUMNI_DATA_DELETE";
export const ALUMNI_DATA_SEARCH = "ALUMNI_DATA_SEARCH";
export const ALUMNI_DATA_EDIT_CANCEL = "ALUMNI_DATA_EDIT_CANCEL";


export const NEW_ALUMNI_LIST = "NEW_ALUMNI_LIST";
export const NEW_ALUMNI_VIEW = "NEW_ALUMNI_VIEW";
export const NEW_ALUMNI_SEARCH = "NEW_ALUMNI_SEARCH";
export const NEW_ALUMNI_VERIFIED = "NEW_ALUMNI_VERIFIED";


export const ROLE_LOADING = "ROLE_LOADING";
export const ROLE_LIST = "ROLE_LIST";
export const ROLE_EDIT = "ROLE_EDIT";
export const ROLE_UPDATE = "ROLE_UPDATE";
export const ROLE_LIST_ADD = "ROLE_LIST_ADD";
export const PERMISSION_LIST = "PERMISSION_LIST";

export const USER_LOADING = "USER_LOADING";
export const USER_LIST = "USER_LIST";
export const USER_ADD = "USER_ADD";
export const USER_EDIT = "USER_EDIT";
export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";


export const NEWS_LOADING = "NEWS_LOADING";
export const NEWS_LIST = "NEWS_LIST";
export const NEWS_ADD = "NEWS_ADD";
export const NEWS_EDIT = "NEWS_EDIT";
export const NEWS_UPDATE = "NEWS_UPDATE";
export const NEWS_DELETE = "NEWS_DELETE";


export const EVENT_TYPE_LOADING = "EVENT_TYPE_LOADING";
export const EVENT_TYPE_LIST = "EVENT_TYPE_LIST";
export const EVENT_TYPE_ADD = "EVENT_TYPE_ADD";
export const EVENT_TYPE_EDIT = "EVENT_TYPE_EDIT";
export const EVENT_TYPE_UPDATE = "EVENT_TYPE_UPDATE";
export const EVENT_TYPE_DELETE = "EVENT_TYPE_DELETE";


export const EVENT_LOADING = "EVENT_LOADING";
export const EVENT_LIST = "EVENT_LIST";
export const EVENT_ADD = "EVENT_ADD";
export const EVENT_EDIT = "EVENT_EDIT";
export const EVENT_UPDATE = "EVENT_UPDATE";
export const EVENT_PUBLISH = "EVENT_PUBLISH";
export const EVENT_DELETE = "EVENT_DELETE";


export const FEATURED_ALUMNI_SEARCH = "FEATURED_ALUMNI_SEARCH";
export const FEATURED_ALUMNI_SELECT = "FEATURED_ALUMNI_SELECT";
export const FEATURED_ALUMNI_ADD = "FEATURED_ALUMNI_ADD";
export const FEATURED_ALUMNI = "FEATURED_ALUMNI";


export const DONATE_LOADING = "DONATE_LOADING";
export const DONATE_LIST = "DONATE_LIST";
export const DONATE_ADD = "DONATE_ADD";
export const DONATE_EDIT = "DONATE_EDIT";
export const DONATE_UPDATE = "DONATE_UPDATE";
export const DONATE_PUBLISH = "DONATE_PUBLISH";
export const DONATE_DELETE = "DONATE_DELETE";